CREATE TABLE IF NOT EXISTS employees (
    id_employee     VARCHAR(10) PRIMARY KEY,
    empl_surname    VARCHAR(50) NOT NULL,
    empl_name       VARCHAR(50) NOT NULL,
    empl_patronymic VARCHAR(50),
    empl_role       VARCHAR(10) NOT NULL,
    salary          NUMERIC(13,4) NOT NULL,
    date_of_birth   DATE NOT NULL,
    date_of_start   DATE NOT NULL,
    phone_number    VARCHAR(13) NOT NULL,
    city            VARCHAR(50) NOT NULL,
    street          VARCHAR(50) NOT NULL,
    zip_code        VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    category_number INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name   VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_cards (
    card_number      VARCHAR(13) PRIMARY KEY,
    cust_surname     VARCHAR(50) NOT NULL,
    cust_name        VARCHAR(50) NOT NULL,
    cust_patronymic  VARCHAR(50),
    phone_number     VARCHAR(13) NOT NULL,
    city             VARCHAR(50),
    street           VARCHAR(50),
    zip_code         VARCHAR(9),
    percent          INTEGER NOT NULL CHECK (percent BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS products (
    id_product       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_number  INTEGER NOT NULL,
    product_name     VARCHAR(50) NOT NULL,
    producer         VARCHAR(50),
    characteristics  VARCHAR(100) NOT NULL,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_number)
        REFERENCES categories (category_number)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS store_products (
    upc                  VARCHAR(12) PRIMARY KEY,
    upc_prom             VARCHAR(12),
    id_product           INTEGER NOT NULL,
    selling_price        NUMERIC(13,4) NOT NULL CHECK (selling_price >= 0),
    products_number      INTEGER NOT NULL CHECK (products_number >= 0),
    promotional_product  BOOLEAN NOT NULL,
    CONSTRAINT fk_store_products_promotional
        FOREIGN KEY (upc_prom)
        REFERENCES store_products (upc)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT fk_store_products_product
        FOREIGN KEY (id_product)
        REFERENCES products (id_product)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT chk_store_products_promo_self_ref
        CHECK (upc_prom IS NULL OR upc_prom <> upc)
);

CREATE TABLE IF NOT EXISTS checks (
    check_number  VARCHAR(10) PRIMARY KEY,
    id_employee   VARCHAR(10) NOT NULL,
    card_number   VARCHAR(13),
    print_date    TIMESTAMP NOT NULL,
    sum_total     NUMERIC(13,4) NOT NULL CHECK (sum_total >= 0),
    vat           NUMERIC(13,4) NOT NULL CHECK (vat >= 0),
    CONSTRAINT fk_checks_employee
        FOREIGN KEY (id_employee)
        REFERENCES employees (id_employee)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT fk_checks_customer_card
        FOREIGN KEY (card_number)
        REFERENCES customer_cards (card_number)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS sales (
    upc             VARCHAR(12) NOT NULL,
    check_number    VARCHAR(10) NOT NULL,
    product_number  INTEGER NOT NULL CHECK (product_number > 0),
    selling_price   NUMERIC(13,4) NOT NULL CHECK (selling_price >= 0),
    PRIMARY KEY (upc, check_number),
    CONSTRAINT fk_sales_store_product
        FOREIGN KEY (upc)
        REFERENCES store_products (upc)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT fk_sales_check
        FOREIGN KEY (check_number)
        REFERENCES checks (check_number)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_products_category_number
    ON products (category_number);

CREATE INDEX IF NOT EXISTS idx_store_products_id_product
    ON store_products (id_product);

CREATE INDEX IF NOT EXISTS idx_checks_id_employee
    ON checks (id_employee);

CREATE INDEX IF NOT EXISTS idx_checks_card_number
    ON checks (card_number);

CREATE INDEX IF NOT EXISTS idx_checks_print_date
    ON checks (print_date);

CREATE INDEX IF NOT EXISTS idx_sales_check_number
    ON sales (check_number);
