// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package productdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	CategoryNumber int32
	CategoryName   string
}

type Check struct {
	CheckNumber string
	IDEmployee  string
	CardNumber  pgtype.Text
	PrintDate   pgtype.Timestamp
	SumTotal    pgtype.Numeric
	Vat         pgtype.Numeric
}

type CustomerCard struct {
	CardNumber     string
	CustSurname    string
	CustName       string
	CustPatronymic pgtype.Text
	PhoneNumber    string
	City           pgtype.Text
	Street         pgtype.Text
	ZipCode        pgtype.Text
	Percent        int32
}

type Employee struct {
	IDEmployee     string
	EmplSurname    string
	EmplName       string
	EmplPatronymic pgtype.Text
	EmplRole       string
	Salary         pgtype.Numeric
	DateOfBirth    pgtype.Date
	DateOfStart    pgtype.Date
	PhoneNumber    string
	City           string
	Street         string
	ZipCode        string
}

type Product struct {
	IDProduct       int32
	CategoryNumber  int32
	ProductName     string
	Producer        pgtype.Text
	Characteristics string
}

type Sale struct {
	Upc           string
	CheckNumber   string
	ProductNumber int32
	SellingPrice  pgtype.Numeric
}

type StoreProduct struct {
	Upc                string
	UpcProm            pgtype.Text
	IDProduct          int32
	SellingPrice       pgtype.Numeric
	ProductsNumber     int32
	PromotionalProduct bool
}
