// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package productdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (category_number, product_name, producer, characteristics)
VALUES ($1, $2, $3, $4)
RETURNING id_product, category_number, product_name, producer, characteristics
`

type CreateProductParams struct {
	CategoryNumber  int32
	ProductName     string
	Producer        pgtype.Text
	Characteristics string
}

// task: Manager can add new product data.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryNumber,
		arg.ProductName,
		arg.Producer,
		arg.Characteristics,
	)
	var i Product
	err := row.Scan(
		&i.IDProduct,
		&i.CategoryNumber,
		&i.ProductName,
		&i.Producer,
		&i.Characteristics,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id_product = $1
`

// task: Manager can delete product data.
func (q *Queries) DeleteProduct(ctx context.Context, idProduct int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, idProduct)
	return err
}

const getAllProductsSortedByName = `-- name: GetAllProductsSortedByName :many
SELECT
    id_product,
    category_number,
    product_name,
    producer,
    characteristics
FROM products
ORDER BY product_name
`

// task: Manager and cashier can get all products sorted by product name.
func (q *Queries) GetAllProductsSortedByName(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProductsSortedByName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.IDProduct,
			&i.CategoryNumber,
			&i.ProductName,
			&i.Producer,
			&i.Characteristics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT
    id_product,
    category_number,
    product_name,
    producer,
    characteristics
FROM products
WHERE id_product = $1
`

// task: Helper query for product CRUD/API flows to fetch one product by identifier.
func (q *Queries) GetProductById(ctx context.Context, idProduct int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, idProduct)
	var i Product
	err := row.Scan(
		&i.IDProduct,
		&i.CategoryNumber,
		&i.ProductName,
		&i.Producer,
		&i.Characteristics,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT
    id_product,
    category_number,
    product_name,
    producer,
    characteristics
FROM products
WHERE category_number = $1
ORDER BY product_name
`

// task: Manager and cashier can search all products from a selected category sorted by product name.
func (q *Queries) GetProductsByCategory(ctx context.Context, categoryNumber int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByCategory, categoryNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.IDProduct,
			&i.CategoryNumber,
			&i.ProductName,
			&i.Producer,
			&i.Characteristics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByName = `-- name: SearchProductsByName :many
SELECT
    id_product,
    category_number,
    product_name,
    producer,
    characteristics
FROM products
WHERE product_name ILIKE '%' || $1 || '%'
ORDER BY product_name
`

// task: Cashier can search products by product name.
func (q *Queries) SearchProductsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProductsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.IDProduct,
			&i.CategoryNumber,
			&i.ProductName,
			&i.Producer,
			&i.Characteristics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_number = $2,
    product_name = $3,
    producer = $4,
    characteristics = $5
WHERE id_product = $1
RETURNING id_product, category_number, product_name, producer, characteristics
`

type UpdateProductParams struct {
	IDProduct       int32
	CategoryNumber  int32
	ProductName     string
	Producer        pgtype.Text
	Characteristics string
}

// task: Manager can edit product data.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.IDProduct,
		arg.CategoryNumber,
		arg.ProductName,
		arg.Producer,
		arg.Characteristics,
	)
	var i Product
	err := row.Scan(
		&i.IDProduct,
		&i.CategoryNumber,
		&i.ProductName,
		&i.Producer,
		&i.Characteristics,
	)
	return i, err
}
