syntax = "proto3";

package auth;

option go_package = "github.com/handziurdmytro/3JlArODA/auth-service/pb;pb";

service AuthService {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc Validate (ValidateRequest) returns (ValidateResponse);
}

message RegisterRequest {
    string username = 1;
    string password = 2;
}

message RegisterResponse {
    string token = 1;
    string role  = 2;
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    string token = 1;
    string role  = 2;
}

message ValidateRequest {
    string token = 1;
}

message ValidateResponse {
    string user_id  = 1;
    string username = 2;
    string role     = 3;
    bool   is_valid = 4;
}
