// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: auth_secret.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainPassword string                 `protobuf:"bytes,1,opt,name=plain_password,json=plainPassword,proto3" json:"plain_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_auth_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_auth_secret_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetPlainPassword() string {
	if x != nil {
		return x.PlainPassword
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashString    string                 `protobuf:"bytes,1,opt,name=hash_string,json=hashString,proto3" json:"hash_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_auth_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_auth_secret_proto_rawDescGZIP(), []int{1}
}

func (x *HashResponse) GetHashString() string {
	if x != nil {
		return x.HashString
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainPassword string                 `protobuf:"bytes,1,opt,name=plain_password,json=plainPassword,proto3" json:"plain_password,omitempty"`
	HashString    string                 `protobuf:"bytes,2,opt,name=hash_string,json=hashString,proto3" json:"hash_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_auth_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_auth_secret_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetPlainPassword() string {
	if x != nil {
		return x.PlainPassword
	}
	return ""
}

func (x *VerifyRequest) GetHashString() string {
	if x != nil {
		return x.HashString
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_auth_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_auth_secret_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_auth_secret_proto protoreflect.FileDescriptor

const file_auth_secret_proto_rawDesc = "" +
	"\n" +
	"\x11auth_secret.proto\x12\vauth_secret\"4\n" +
	"\vHashRequest\x12%\n" +
	"\x0eplain_password\x18\x01 \x01(\tR\rplainPassword\"/\n" +
	"\fHashResponse\x12\x1f\n" +
	"\vhash_string\x18\x01 \x01(\tR\n" +
	"hashString\"W\n" +
	"\rVerifyRequest\x12%\n" +
	"\x0eplain_password\x18\x01 \x01(\tR\rplainPassword\x12\x1f\n" +
	"\vhash_string\x18\x02 \x01(\tR\n" +
	"hashString\"+\n" +
	"\x0eVerifyResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid2\xa3\x01\n" +
	"\x11AuthSecretService\x12C\n" +
	"\fHashPassword\x12\x18.auth_secret.HashRequest\x1a\x19.auth_secret.HashResponse\x12I\n" +
	"\x0eVerifyPassword\x12\x1a.auth_secret.VerifyRequest\x1a\x1b.auth_secret.VerifyResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_auth_secret_proto_rawDescOnce sync.Once
	file_auth_secret_proto_rawDescData []byte
)

func file_auth_secret_proto_rawDescGZIP() []byte {
	file_auth_secret_proto_rawDescOnce.Do(func() {
		file_auth_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_secret_proto_rawDesc), len(file_auth_secret_proto_rawDesc)))
	})
	return file_auth_secret_proto_rawDescData
}

var file_auth_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_secret_proto_goTypes = []any{
	(*HashRequest)(nil),    // 0: auth_secret.HashRequest
	(*HashResponse)(nil),   // 1: auth_secret.HashResponse
	(*VerifyRequest)(nil),  // 2: auth_secret.VerifyRequest
	(*VerifyResponse)(nil), // 3: auth_secret.VerifyResponse
}
var file_auth_secret_proto_depIdxs = []int32{
	0, // 0: auth_secret.AuthSecretService.HashPassword:input_type -> auth_secret.HashRequest
	2, // 1: auth_secret.AuthSecretService.VerifyPassword:input_type -> auth_secret.VerifyRequest
	1, // 2: auth_secret.AuthSecretService.HashPassword:output_type -> auth_secret.HashResponse
	3, // 3: auth_secret.AuthSecretService.VerifyPassword:output_type -> auth_secret.VerifyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_secret_proto_init() }
func file_auth_secret_proto_init() {
	if File_auth_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_secret_proto_rawDesc), len(file_auth_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_secret_proto_goTypes,
		DependencyIndexes: file_auth_secret_proto_depIdxs,
		MessageInfos:      file_auth_secret_proto_msgTypes,
	}.Build()
	File_auth_secret_proto = out.File
	file_auth_secret_proto_goTypes = nil
	file_auth_secret_proto_depIdxs = nil
}
