// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: auth_secret.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthSecretService_HashPassword_FullMethodName   = "/auth_secret.AuthSecretService/HashPassword"
	AuthSecretService_VerifyPassword_FullMethodName = "/auth_secret.AuthSecretService/VerifyPassword"
)

// AuthSecretServiceClient is the client API for AuthSecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthSecretServiceClient interface {
	HashPassword(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	VerifyPassword(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type authSecretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthSecretServiceClient(cc grpc.ClientConnInterface) AuthSecretServiceClient {
	return &authSecretServiceClient{cc}
}

func (c *authSecretServiceClient) HashPassword(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, AuthSecretService_HashPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSecretServiceClient) VerifyPassword(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, AuthSecretService_VerifyPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSecretServiceServer is the server API for AuthSecretService service.
// All implementations must embed UnimplementedAuthSecretServiceServer
// for forward compatibility.
type AuthSecretServiceServer interface {
	HashPassword(context.Context, *HashRequest) (*HashResponse, error)
	VerifyPassword(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedAuthSecretServiceServer()
}

// UnimplementedAuthSecretServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthSecretServiceServer struct{}

func (UnimplementedAuthSecretServiceServer) HashPassword(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashPassword not implemented")
}
func (UnimplementedAuthSecretServiceServer) VerifyPassword(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPassword not implemented")
}
func (UnimplementedAuthSecretServiceServer) mustEmbedUnimplementedAuthSecretServiceServer() {}
func (UnimplementedAuthSecretServiceServer) testEmbeddedByValue()                           {}

// UnsafeAuthSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthSecretServiceServer will
// result in compilation errors.
type UnsafeAuthSecretServiceServer interface {
	mustEmbedUnimplementedAuthSecretServiceServer()
}

func RegisterAuthSecretServiceServer(s grpc.ServiceRegistrar, srv AuthSecretServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthSecretServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthSecretService_ServiceDesc, srv)
}

func _AuthSecretService_HashPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSecretServiceServer).HashPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSecretService_HashPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSecretServiceServer).HashPassword(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSecretService_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSecretServiceServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSecretService_VerifyPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSecretServiceServer).VerifyPassword(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthSecretService_ServiceDesc is the grpc.ServiceDesc for AuthSecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthSecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_secret.AuthSecretService",
	HandlerType: (*AuthSecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HashPassword",
			Handler:    _AuthSecretService_HashPassword_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _AuthSecretService_VerifyPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_secret.proto",
}
