// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package customercarddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerCard = `-- name: CreateCustomerCard :one
INSERT INTO customer_cards (
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
`

type CreateCustomerCardParams struct {
	CardNumber     string
	CustSurname    string
	CustName       string
	CustPatronymic pgtype.Text
	PhoneNumber    string
	City           pgtype.Text
	Street         pgtype.Text
	ZipCode        pgtype.Text
	Percent        int32
}

// task: Manager and cashier can add new customer card data.
func (q *Queries) CreateCustomerCard(ctx context.Context, arg CreateCustomerCardParams) (CustomerCard, error) {
	row := q.db.QueryRow(ctx, createCustomerCard,
		arg.CardNumber,
		arg.CustSurname,
		arg.CustName,
		arg.CustPatronymic,
		arg.PhoneNumber,
		arg.City,
		arg.Street,
		arg.ZipCode,
		arg.Percent,
	)
	var i CustomerCard
	err := row.Scan(
		&i.CardNumber,
		&i.CustSurname,
		&i.CustName,
		&i.CustPatronymic,
		&i.PhoneNumber,
		&i.City,
		&i.Street,
		&i.ZipCode,
		&i.Percent,
	)
	return i, err
}

const deleteCustomerCard = `-- name: DeleteCustomerCard :exec
DELETE FROM customer_cards
WHERE card_number = $1
`

// task: Manager can delete customer card data.
func (q *Queries) DeleteCustomerCard(ctx context.Context, cardNumber string) error {
	_, err := q.db.Exec(ctx, deleteCustomerCard, cardNumber)
	return err
}

const getAllCustomerCards = `-- name: GetAllCustomerCards :many
SELECT
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
FROM customer_cards
ORDER BY cust_surname, cust_name, cust_patronymic
`

// task: Manager and cashier can get all customer cards sorted by customer surname.
func (q *Queries) GetAllCustomerCards(ctx context.Context) ([]CustomerCard, error) {
	rows, err := q.db.Query(ctx, getAllCustomerCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerCard
	for rows.Next() {
		var i CustomerCard
		if err := rows.Scan(
			&i.CardNumber,
			&i.CustSurname,
			&i.CustName,
			&i.CustPatronymic,
			&i.PhoneNumber,
			&i.City,
			&i.Street,
			&i.ZipCode,
			&i.Percent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerCardByNumber = `-- name: GetCustomerCardByNumber :one
SELECT
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
FROM customer_cards
WHERE card_number = $1
`

// task: Helper query for customer card CRUD/API flows to fetch one customer card by card number.
func (q *Queries) GetCustomerCardByNumber(ctx context.Context, cardNumber string) (CustomerCard, error) {
	row := q.db.QueryRow(ctx, getCustomerCardByNumber, cardNumber)
	var i CustomerCard
	err := row.Scan(
		&i.CardNumber,
		&i.CustSurname,
		&i.CustName,
		&i.CustPatronymic,
		&i.PhoneNumber,
		&i.City,
		&i.Street,
		&i.ZipCode,
		&i.Percent,
	)
	return i, err
}

const getCustomerCardsByPercent = `-- name: GetCustomerCardsByPercent :many
SELECT
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
FROM customer_cards
WHERE percent = $1
ORDER BY cust_surname, cust_name, cust_patronymic
`

// task: Manager can get all customer cards with a selected discount percent sorted by customer surname.
func (q *Queries) GetCustomerCardsByPercent(ctx context.Context, percent int32) ([]CustomerCard, error) {
	rows, err := q.db.Query(ctx, getCustomerCardsByPercent, percent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerCard
	for rows.Next() {
		var i CustomerCard
		if err := rows.Scan(
			&i.CardNumber,
			&i.CustSurname,
			&i.CustName,
			&i.CustPatronymic,
			&i.PhoneNumber,
			&i.City,
			&i.Street,
			&i.ZipCode,
			&i.Percent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomerCardsBySurname = `-- name: SearchCustomerCardsBySurname :many
SELECT
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
FROM customer_cards
WHERE cust_surname ILIKE '%' || $1 || '%'
ORDER BY cust_surname, cust_name, cust_patronymic
`

// task: Cashier can search customer cards by customer surname.
func (q *Queries) SearchCustomerCardsBySurname(ctx context.Context, dollar_1 pgtype.Text) ([]CustomerCard, error) {
	rows, err := q.db.Query(ctx, searchCustomerCardsBySurname, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerCard
	for rows.Next() {
		var i CustomerCard
		if err := rows.Scan(
			&i.CardNumber,
			&i.CustSurname,
			&i.CustName,
			&i.CustPatronymic,
			&i.PhoneNumber,
			&i.City,
			&i.Street,
			&i.ZipCode,
			&i.Percent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerCard = `-- name: UpdateCustomerCard :one
UPDATE customer_cards
SET cust_surname = $2,
    cust_name = $3,
    cust_patronymic = $4,
    phone_number = $5,
    city = $6,
    street = $7,
    zip_code = $8,
    percent = $9
WHERE card_number = $1
RETURNING
    card_number,
    cust_surname,
    cust_name,
    cust_patronymic,
    phone_number,
    city,
    street,
    zip_code,
    percent
`

type UpdateCustomerCardParams struct {
	CardNumber     string
	CustSurname    string
	CustName       string
	CustPatronymic pgtype.Text
	PhoneNumber    string
	City           pgtype.Text
	Street         pgtype.Text
	ZipCode        pgtype.Text
	Percent        int32
}

// task: Manager and cashier can edit customer card data.
func (q *Queries) UpdateCustomerCard(ctx context.Context, arg UpdateCustomerCardParams) (CustomerCard, error) {
	row := q.db.QueryRow(ctx, updateCustomerCard,
		arg.CardNumber,
		arg.CustSurname,
		arg.CustName,
		arg.CustPatronymic,
		arg.PhoneNumber,
		arg.City,
		arg.Street,
		arg.ZipCode,
		arg.Percent,
	)
	var i CustomerCard
	err := row.Scan(
		&i.CardNumber,
		&i.CustSurname,
		&i.CustName,
		&i.CustPatronymic,
		&i.PhoneNumber,
		&i.City,
		&i.Street,
		&i.ZipCode,
		&i.Percent,
	)
	return i, err
}
